version: '3.7'
services:
  config-server:
    image: config-server:v1
    ports:
      - "8888:8888"
    restart: always
    networks:
      - springcloud

  eureka-server:
    container_name: eureka-server
    image: eureka-server:v1
    ports:
      - "8761:8761"
    restart: always
    networks:
      - springcloud
  
  mysql:
    container_name: microservices-mysql
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    networks:
      - springcloud
    environment:
      MYSQL_DATABASE: users
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  postgres:
    container_name: microservices-postgres
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    restart: always
    networks:
      - springcloud
    environment:
      POSTGRES_DB: videogames
      POSTGRES_PASSWORD: root

  user-videogames:
    image: user-videogames:v1
    ports:
      - "8002:8002"
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - mysql

  videogames:
    image: videogames:v1
    ports:
      - "8007:8007"
    restart: always
    networks:
      - springcloud
    depends_on: 
      - config-server
      - eureka-server
      - postgres
  
  gateway-server:
    image: gateway-server:v1
    ports:
      - "8090:8090"
    restart: always
    networks:
      - springcloud
    depends_on:
      - config-server
      - eureka-server
      - user-videogames
      - videogames

  rabbitmq:
    container_name: microservice-rabbitmq
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - springcloud

  zipkin:
    container_name: zipkin-server
    image: zipkin:v1
    ports:
      - "9411:9411"
    restart: always
    networks:
      - springcloud
    depends_on:
      - mysql
      - rabbitmq
    environment:
      RABBIT_ADDRESSES: microservice-rabbitmq:5672

networks:
  springcloud:
